# Generated by Django 6.0.4 on 2026-04-22 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('player', 'Mängija'), ('team', 'Meeskond')], default='player', max_length=20)),
                ('contact_info', models.CharField(blank=True, max_length=150)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sport_type', models.CharField(choices=[('football', 'Jalgpall'), ('basketball', 'Korvpall'), ('volleyball', 'Võrkpall'), ('tennis', 'Tennis'), ('padel', 'Padel'), ('mma', 'MMA'), ('esport', 'E-sport'), ('other', 'Muu')], default='other', max_length=30)),
                ('format', models.CharField(choices=[('single_elimination', 'Single Elimination'), ('round_robin', 'Round Robin'), ('group_stage', 'Alagrupid'), ('other', 'Muu')], default='single_elimination', max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Mustand'), ('registration_open', 'Registreerimine avatud'), ('ready', 'Valmis alustamiseks'), ('active', 'Käimas'), ('finished', 'Lõpetatud'), ('cancelled', 'Tühistatud')], default='draft', max_length=30)),
                ('max_participants', models.PositiveIntegerField(default=2)),
                ('admin_password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('bracket_position', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planeeritud'), ('ongoing', 'Käimas'), ('finished', 'Lõpetatud'), ('cancelled', 'Tühistatud')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_participant1', to='tournaments.participant')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_participant2', to='tournaments.participant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['round', 'scheduled_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1_score', models.PositiveIntegerField(default=0)),
                ('participant2_score', models.PositiveIntegerField(default=0)),
                ('result_confirmed', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournaments.match')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reported_by_name', models.CharField(blank=True, max_length=120)),
                ('reported_by_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'Uus'), ('reviewed', 'Üle vaadatud'), ('resolved', 'Lahendatud')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to='tournaments.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('tournament', 'name')},
        ),
    ]
